spring:
  application:
    name: file-portal
  profiles:    active: "@active@"
  cloud:    loadbalancer:      cache:        ttl: PT2S
  data:    mongodb:      auto-index-creation: true

server:  port: 8081
  servlet:    context-path: /